## https://docs.docker.com/compose/
## https://docs.docker.com/compose/compose-file/

version: "3.7"

services: 

  hostapd:
    build:
      context: ./build/
      dockerfile: Dockerfile-hostapd
    volumes: 
    - ./config/:/config/:ro
    cap_add: 
    - NET_ADMIN
    network_mode: "host"
    environment: 
      WIFI_DEV: wlx0013ef710ea5
  
  dnsmasqd:
    build:
      context: ./build/
      dockerfile: Dockerfile-dnsmasqd
    volumes: 
    - ./config/:/config/:ro
    depends_on: 
      - hostapd
    network_mode: "host"
    cap_add: 
      - NET_ADMIN
      - NET_BROADCAST
    environment: 
      WIFI_DEV: wlx0013ef710ea5
  
  mosquitto:
    image: eclipse-mosquitto:1.6
    volumes: 
    - ./config/:/mosquitto/config/:ro
    - ./data/:/mosquitto/data/:rw
    - ./log/:/mosquitto/log/:rw
    depends_on: 
      - hostapd
      - dnsmasqd
    network_mode: "host"
    environment: 
      WIFI_DEV: wlx0013ef710ea5
    